/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as BooksShelfRouteImport } from './routes/books/shelf'
import { Route as BooksExploreRouteImport } from './routes/books/explore'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpSuccessRouteImport } from './routes/(auth)/sign-up-success'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as BooksBookIdEditRouteImport } from './routes/books/$bookId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const BooksShelfRoute = BooksShelfRouteImport.update({
  id: '/books/shelf',
  path: '/books/shelf',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksExploreRoute = BooksExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpSuccessRoute = authSignUpSuccessRouteImport.update({
  id: '/(auth)/sign-up-success',
  path: '/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BooksBookIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/explore': typeof BooksExploreRoute
  '/books/shelf': typeof BooksShelfRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/books/': typeof BooksIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/explore': typeof BooksExploreRoute
  '/books/shelf': typeof BooksShelfRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/books': typeof BooksIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/sign-up-success': typeof authSignUpSuccessRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/explore': typeof BooksExploreRoute
  '/books/shelf': typeof BooksShelfRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/books/': typeof BooksIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-success'
    | '/verify-email'
    | '/books/$bookId'
    | '/books/explore'
    | '/books/shelf'
    | '/profile/$userId'
    | '/books/'
    | '/profile/'
    | '/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-success'
    | '/verify-email'
    | '/books/$bookId'
    | '/books/explore'
    | '/books/shelf'
    | '/profile/$userId'
    | '/books'
    | '/profile'
    | '/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/sign-up-success'
    | '/(auth)/verify-email'
    | '/books/$bookId'
    | '/books/explore'
    | '/books/shelf'
    | '/profile/$userId'
    | '/books/'
    | '/profile/'
    | '/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authSignUpSuccessRoute: typeof authSignUpSuccessRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  BooksShelfRoute: typeof BooksShelfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/books/shelf': {
      id: '/books/shelf'
      path: '/books/shelf'
      fullPath: '/books/shelf'
      preLoaderRoute: typeof BooksShelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/explore': {
      id: '/books/explore'
      path: '/explore'
      fullPath: '/books/explore'
      preLoaderRoute: typeof BooksExploreRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up-success': {
      id: '/(auth)/sign-up-success'
      path: '/sign-up-success'
      fullPath: '/sign-up-success'
      preLoaderRoute: typeof authSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/edit': {
      id: '/books/$bookId/edit'
      path: '/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authSignUpSuccessRoute: authSignUpSuccessRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  BooksShelfRoute: BooksShelfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
