/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksAddRouteImport } from './routes/books/add'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as authSignUpSuccessRouteImport } from './routes/(auth)/sign-up-success'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as BooksBookIdEditRouteImport } from './routes/books/$bookId/edit'

const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksAddRoute = BooksAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const authSignUpSuccessRoute = authSignUpSuccessRouteImport.update({
  id: '/(auth)/sign-up-success',
  path: '/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BooksBookIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/add': typeof BooksAddRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/add': typeof BooksAddRoute
  '/books': typeof BooksIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/sign-up-success': typeof authSignUpSuccessRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/add': typeof BooksAddRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-success'
    | '/books/$bookId'
    | '/books/add'
    | '/books/'
    | '/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-success'
    | '/books/$bookId'
    | '/books/add'
    | '/books'
    | '/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/sign-up-success'
    | '/books/$bookId'
    | '/books/add'
    | '/books/'
    | '/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authSignUpSuccessRoute: typeof authSignUpSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/add': {
      id: '/books/add'
      path: '/add'
      fullPath: '/books/add'
      preLoaderRoute: typeof BooksAddRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/(auth)/sign-up-success': {
      id: '/(auth)/sign-up-success'
      path: '/sign-up-success'
      fullPath: '/sign-up-success'
      preLoaderRoute: typeof authSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/edit': {
      id: '/books/$bookId/edit'
      path: '/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
  }
}

interface BooksBookIdRouteChildren {
  BooksBookIdEditRoute: typeof BooksBookIdEditRoute
}

const BooksBookIdRouteChildren: BooksBookIdRouteChildren = {
  BooksBookIdEditRoute: BooksBookIdEditRoute,
}

const BooksBookIdRouteWithChildren = BooksBookIdRoute._addFileChildren(
  BooksBookIdRouteChildren,
)

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRouteWithChildren
  BooksAddRoute: typeof BooksAddRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRouteWithChildren,
  BooksAddRoute: BooksAddRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authSignUpSuccessRoute: authSignUpSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
